### ISSUE TITLE
How to improve performance?

### ISSUE THREAD

**Issue by nijippoi** [bashonly/yt-dlp-TTUser#4]
This is just a request for comment. Do you have any suggestions to improve the speed when using this plugin?

Fetching user video list takes a long time (the "Downloading video feed" part for each video details after getting the paged video list) compared to upstream TikTokUserIE logic (when it was working, up to circa end of October 2023).

Before, it took less than 2mins to finish and now it takes more than 2hours (~50 users, with total of ~5000 videos).

I am using an archive list so yt-dlp is not downloading most of the videos, only new ones, so almost 99% of the time taken is in scraping the video list.

**Comment by AAndyProgram** [comment]
```bash
yt-dlp --datebefore YYYYMMDD --dateafter YYYYMMDD URL
```

**Comment by bashonly** [comment]
`--lazy-playlist --break-on-reject --break-per-input`

**Comment by bashonly** [comment]
The difference between native `TikTokUserIE` and the plugin is that the native extractor was using the mobile API, while the plugin has to use the web API. Only the mobile API serves the HQ/watermark-free formats, so the plugin needs to re-extract all the videos from mobile, whereas the native extractor was already getting all the info it needed as it paginated through the user feed.

There is no solution to this, because the mobile API user list endpoint is no longer usable.

**Comment by Zachary247** [comment]
There could be a way to improve time with 50 users. After your first download of all 50 you would only need to loop for new videos with a new script. If there was a way to only download the first page of user video feed (becuase a user is not likely to upload more then 20 videos a day) and not scroll for the rest of the video playlist pages you could save some time on channels that have +400 videos by only looking for the first page. A few seconds saved from fetching pages could equal to time saved  and could really add up over 50+ big userchannels. I just don't know what the code for only downloading the first page of a username is.
